🐛remove usage of /tmp in capbk
kubernetes-sigs/cluster-api pull request #3776
Opened 2020-10-12 15:07 UTC by arghya88

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3769

2020-10-12 15:24 UTC, benmoss requested changes
I don't think `/run/kubeadm` will exist by default and so might need to be created, unlike `/tmp`. Have you tested these changes?

2020-10-12 15:24 UTC, benmoss commented on test/infrastructure/docker/cloudinit/kindadapter_test.go
>  		{Cmd: "mkdir", Args: []string{"-p", "/tmp"}},
```suggestion
		{Cmd: "mkdir", Args: []string{"-p", "/run/kubeadm"}},
```

2020-10-12 15:24 UTC, benmoss commented
/ok-to-test

2020-10-12 15:28 UTC, arghya88 commented on test/infrastructure/docker/cloudinit/kindadapter_test.go
>  		{Cmd: "mkdir", Args: []string{"-p", "/tmp"}},
Updated..Thanks

2020-10-12 15:51 UTC, vincepri commented
/milestone v0.4.0

2020-10-12 15:57 UTC, arghya88 commented
/assign @ncdc

2020-10-12 18:28 UTC, vincepri approved these changes
/approve
/assign @fabriziopandini

2020-10-12 20:42 UTC, CecileRobertMichon commented
@arghya88 please add a PR description describing why this change is desirable

2020-10-13 03:13 UTC, arghya88 commented
@CecileRobertMichon Thanks for feedback..I have added a description

2020-10-13 07:23 UTC, fabriziopandini commented
Thanks @arghya88 !
PR looks good to me! My only concern is how do we start to document v1alpha4 breaking changes like this. Should we change the PR title as :warning ?
@vincepri ^^

2020-10-13 09:39 UTC, arghya88 commented
@fabriziopandini I am fine doing that if that's good enough. Have we done something else before to handle breaking change scenario?

2020-10-13 10:05 UTC, fabriziopandini commented
Renaming the PR should be enough IMO, but let's wait for confirmation

2020-10-13 13:38 UTC, ncdc commented
@fabriziopandini this doesn't look like a breaking change to me?

2020-10-13 14:04 UTC, fabriziopandini commented
@ncdc this is not breaking any API, but there are users relying on the current file location for their `PreKubeadmCommands`, so I want to be sure they are properly informed.

2020-10-14 12:35 UTC, arghya88 commented
@vincepri should we then change the title of the PR to warning?

cc @fabriziopandini

2020-10-14 14:12 UTC, fabriziopandini commented
+1 to add warning and retitle in something like "capk generates kubadm config files under /run/kubeadm/ instead of /tmp"

2020-10-14 14:42 UTC, vincepri commented
Thanks for marking it as a breaking change!

2020-10-14 14:42 UTC, vincepri commented
/ test pull-cluster-api-e2e-full-main

2020-10-14 14:42 UTC, vincepri commented
/test pull-cluster-api-e2e-full-main

2020-10-14 16:02 UTC, vincepri commented
/test pull-cluster-api-e2e-full-main

2020-10-15 14:48 UTC, vincepri approved these changes
/lgtm

2020-10-15 15:00 UTC, merged