🌱 Make KCP using embedded kubeadm types while manipulating the kubeadm-config ConfigMap
kubernetes-sigs/cluster-api pull request #4443
Opened 2021-04-07 15:31 UTC by fabriziopandini

**What this PR does / why we need it**:
This PR is a follow up of https://github.com/kubernetes-sigs/cluster-api/pull/4255 and the last step for implementing the [Insulate users from kubeadm API version changes KEP](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/proposals/20210210-insulate-users-from-kubeadm-API-changes.md)

More specifically, this PR changes KCP in order to use the embedded kubeadm types and the underlying conversion mechanism while manipulating the Kubeadm-config ConfigMap.

Given the existing nested interfaces in KCP, this PR touch many methods, however during the change:
- all the ConfigMap transformations are now managed by a single method and executed only if required (before most code was duplicated, in many case with slight variations)
- version management was consistently moved to use semver.Version (before it was a mix of string, semver.Version, and version.Version)

**Which issue(s) this PR fixes**:
Fixes #

2021-04-26 13:15 UTC, fabriziopandini commented
/retest

2021-04-26 13:20 UTC, fabriziopandini commented
It seems there are lint and test errors happening in CI and not locally 🤔, I have to investigate

2021-04-26 15:38 UTC, sbueringer commented
@fabriziopandini I think it's using a newer linter (v1.38.0) https://github.com/kubernetes-sigs/cluster-api/pull/4443/checks?check_run_id=2438374848
vs the one we have in go.mod (v1.32.0)

2021-04-27 17:30 UTC, vincepri requested changes

2021-04-27 17:30 UTC, vincepri commented on bootstrap/kubeadm/types/utils.go
> +	case version.LT(semver.MustParse("1.13.0")):
Should we make these package variables so we only use MustParse once during the package initialization?

2021-04-27 17:30 UTC, vincepri commented on bootstrap/kubeadm/types/utils.go
> +	case version.LT(semver.MustParse("1.15.0")):
Same as above

2021-04-27 17:30 UTC, vincepri commented on controlplane/kubeadm/internal/workload_cluster.go
> +	configMapKey := ctrlclient.ObjectKey{Name: kubeadmConfigKey, Namespace: metav1.NamespaceSystem}
```suggestion
	key := ctrlclient.ObjectKey{Name: kubeadmConfigKey, Namespace: metav1.NamespaceSystem}
```

2021-04-27 17:30 UTC, vincepri commented on controlplane/kubeadm/internal/workload_cluster.go
> +	kubeadmConfigMap, err := w.getConfigMap(ctx, configMapKey)
```suggestion
	configMap, err := w.getConfigMap(ctx, key)
```

2021-04-27 17:30 UTC, vincepri commented on controlplane/kubeadm/internal/workload_cluster.go
> +	config := &kubeadmConfig{ConfigMap: kubeadmConfigMap}
```suggestion
	config := &kubeadmConfig{ConfigMap: configMap}
```

2021-04-27 17:30 UTC, vincepri commented on controlplane/kubeadm/internal/workload_cluster_coredns.go
> +		return k.UpdateCoreDNSImageInfo(dns.ImageRepository, dns.ImageTag, version)
Could we inline the `UpdateCoreDNSImageInfo` function instead of having it as part of kubeadmConfig struct?

2021-04-27 17:30 UTC, vincepri commented on controlplane/kubeadm/internal/workload_cluster.go
> +		return k.UpdateImageRepository(imageRepository, version)
Inline this?

2021-04-27 17:30 UTC, vincepri commented on controlplane/kubeadm/internal/workload_cluster.go
> +		return k.UpdateKubernetesVersion(version)
Inline this?

2021-04-27 17:30 UTC, vincepri commented on controlplane/kubeadm/internal/workload_cluster.go
> +		return k.UpdateAPIServer(apiServer, version)
Inline this?

2021-04-27 17:30 UTC, vincepri commented on controlplane/kubeadm/internal/workload_cluster.go
> +		return k.UpdateControllerManager(controllerManager, version)
Inline this?

2021-04-27 17:30 UTC, vincepri commented on controlplane/kubeadm/internal/workload_cluster.go
> +		return k.UpdateScheduler(scheduler, version)
Inline this?

2021-04-27 17:30 UTC, vincepri commented on controlplane/kubeadm/internal/workload_cluster.go
> +	changed, err := mutator(config)
Why not detect the changes on this end rather than relying on the `mutator` caller to tell us if the map has changed or not?

2021-04-29 10:09 UTC, fabriziopandini commented
@vincepri thanks for feedback
I took over from your suggestion and completely dropped the KubeadmConfig structure, thus reducing the number of internal abstraction in KCP. Unfortunately this lead to refactoring some test, but I think this is worth the effort....

2021-04-29 10:10 UTC, fabriziopandini commented
/retest

2021-04-30 21:10 UTC, CecileRobertMichon reviewed
lgtm

2021-05-04 08:59 UTC, fabriziopandini commented
@CecileRobertMichon added comments to updateClusterConfiguration/updateClusterStatus, PTAL

2021-05-10 20:15 UTC, vincepri approved these changes

2021-05-11 12:30 UTC, fabriziopandini commented
@vincepri rebased fixing recently added remediation tests to get Kubernetes version as a input

2021-05-11 14:47 UTC, merged