Add ability for nodeToMachines to filter by clusterName and namespace
kubernetes-sigs/cluster-api pull request #4513
Opened 2021-04-22 14:16 UTC by enxebre

**What this PR does / why we need it**:
This is a best effort to filter machines by clusterName and namespace when reconciling from a node event.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3831

2021-04-22 16:01 UTC, mrajashree commented
lgtm

2021-04-22 17:24 UTC, vincepri requested changes

2021-04-22 17:24 UTC, vincepri commented on controllers/machine_controller.go
> +	}
Add a test?

2021-04-22 17:24 UTC, vincepri commented on controllers/machine_controller.go
> +	if ok {
```suggestion
	if namespace, ok := node.GetAnnotations()[clusterv1.ClusterNamespaceAnnotation]; ok {
```

2021-04-22 17:24 UTC, vincepri commented on controllers/machine_controller.go
> +	if ok {
Add a test

2021-04-22 17:24 UTC, vincepri commented on controllers/machine_controller.go
> +	}
These annotations were added later, so I'd like to make sure we cover:

- A node with none of these annotations
- A node with a single annotation
- A node with both annotations

2021-04-23 13:05 UTC, enxebre commented
@vincepri added tests for all the cases. I used a testEnv since fakeClient does not support indexes.
I also created https://github.com/kubernetes-sigs/cluster-api/issues/4518 and so then we can also filter by providerID.

2021-05-11 03:35 UTC, sbueringer commented on controllers/machine_controller_test.go
> +			Namespace: ns.Name,
As Nodes are cluster-wide setting the Namespace doesn't make a lot of sense imho. Should we also prefix this again to make sure we don't clash with other tests?

2021-05-11 03:38 UTC, sbueringer commented on controllers/machine_controller_test.go
> +	FakeNodes := []*corev1.Node{
```suggestion
	fakeNodes := []*corev1.Node{
```

2021-05-11 20:57 UTC, sbueringer commented
/lgtm

2021-05-18 13:48 UTC, vincepri approved these changes
/approve

2021-05-18 13:59 UTC, merged