Update troubleshooting with granular debug information for windows an…
kubernetes-sigs/cluster-api pull request #5190
Opened 2021-09-02 12:52 UTC by jayunit100

Some improvements on how to debug hairy bootstrap issues.

2021-09-02 14:13 UTC, killianmuldoon requested changes
Looks good - I'm not able to test this on a Windows VM, but well structured solutions for common errors are definitely welcome. I think there's a couple of nits and issues with structure to clean up.

2021-09-02 14:13 UTC, killianmuldoon commented on docs/book/src/user/troubleshooting.md
> +  - The windows node is missing some Binaries which you expected to have in the image on boot.
nit
```suggestion
  - The windows node is missing some binaries which you expected to have in the image on boot.
```

2021-09-02 14:13 UTC, killianmuldoon commented on docs/book/src/user/troubleshooting.md
> +Irrespective of OS, on any Vsphere VM, for you can confirm the bootstrap information in the `Configuration Parameters` section of your VSphere machine settings, which are available from the `VM Hardw
Is this entire troubleshooting section only relevant to vSphere Windows nodes? We might want to make that really explicit everywhere it's the case if so.

2021-09-02 14:13 UTC, killianmuldoon commented on docs/book/src/user/troubleshooting.md
> +Other clouds will have similar methodologies for inspecting the user data attached to a VM.
Maybe make the vSphere issue a subsection and open an issue to add the information to troubleshoot this issue for other cloud providers ?

2021-09-02 14:13 UTC, killianmuldoon commented on docs/book/src/user/troubleshooting.md
> +  - The windows node is missing some Binaries which you expected to have in the image on boot.
nit 
```suggestion
  - The Windows node is missing some binaries which you expected to have in the image on boot.
```

2021-09-02 14:13 UTC, killianmuldoon commented on docs/book/src/user/troubleshooting.md
> +  - The windows node might be accidentally running powershell or choco commands during bootstrap that aren't installed.
nit 
```suggestion
  - The Windows node might be accidentally running PowerShell or Chocalatey / choco commands during bootstrap that aren't installed. 
```

2021-09-02 14:13 UTC, killianmuldoon commented on docs/book/src/user/troubleshooting.md
> +## Troubleshooting Windows Node Bootstrapping Errors
nit - don't use title case to make consistent with the rest of the text:
```suggestion
## Troubleshooting Windows node bootstrapping errors
```

2021-09-02 14:13 UTC, killianmuldoon commented on docs/book/src/user/troubleshooting.md
> +message in the logs for your `capi-kubeadm-bootstrap-system` controller.
There's some context missing here as to the meaning of this message or the follow on. All of the headings are on the same level so it looks like there's no logical flow for solving this problem once ID'd - maybe add links or change the section headings.

2021-09-02 14:13 UTC, killianmuldoon commented on docs/book/src/user/troubleshooting.md
> +Sometimes, you'll see that the bootstrapping secret is noted as not having been consumed yet, *even though* you correctly ran the bootstrapping phase on your node.  This happens because Cluster API d
Use of VM here is maybe too specific? Is this somehow limited to VMs vs BmMs?

2021-09-02 14:13 UTC, killianmuldoon commented on docs/book/src/user/troubleshooting.md
> +## Avoid mislabeling nodes with reserved labels such as `node-role.kubernetes.io` fails with kubeadm error during bootstrap
I would revert this - IMHO the original phrase is clearer.

2021-12-14 14:56 UTC, fabriziopandini commented
@jayunit100 do you have some time to address the comments above?

2022-03-01 22:13 UTC, enxebre commented
Hey @jayunit100 are you still pursing this PR?

2022-04-01 16:03 UTC, vincepri commented
Closing for now due to inactivity, please feel free to reopen once ready.

/close

2022-04-01 16:03 UTC, closed without merging

2022-04-02 01:53 UTC, jayunit100 commented
Just saw , Sgtm sorry got busy w other stuff :)