✨ Introduce version check validation for generate provider command
kubernetes-sigs/cluster-api pull request #5933
Opened 2022-01-13 11:56 UTC by tharun208

Signed-off-by: tharun <rajendrantharun@live.com>

This PR introduces validation for incompatible versions while generating providers using the `generate provider` command.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5864

2022-01-14 15:01 UTC, fabriziopandini commented
/ok-to-test
/cc @ykakarap

2022-01-17 15:19 UTC, ykakarap commented
@tharun208 Thank you for getting the PR out. 🙂 
I will review this soon.

2022-01-19 08:52 UTC, ykakarap requested changes
First pass review: 
It mostly looks good, expect for the default version case.

2022-01-19 08:52 UTC, ykakarap commented on cmd/clusterctl/client/config.go
> +	repositoryClientFactory, err := c.repositoryClientFactory(RepositoryClientFactoryInput{Provider: providerConfig})
```suggestion
	repositoryClient, err := c.repositoryClientFactory(RepositoryClientFactoryInput{Provider: providerConfig})
```

nit: the factory returns a client not another factory.

2022-01-19 08:52 UTC, ykakarap commented on cmd/clusterctl/client/config.go
> +	// components. So we revert to using the default SimpleYamlProcessor.
```suggestion
```

IMHO, I dont think you need these comments here. Also, If the defaulting changes these comments will become false.

2022-01-19 08:52 UTC, ykakarap commented on cmd/clusterctl/client/config.go
> +		return nil, err
```suggestion
		return nil, errrors.Wrap(err, "failed to parse provider name")
```

Wrapping the errors provides more context when something fails. 
If you can also wrap other errors below that would be great.

2022-01-19 08:52 UTC, ykakarap commented on cmd/clusterctl/client/config.go
> +		return nil, errors.Errorf("current version of clusterctl is only compatible with %s providers, detected %s for provider %s", clusterv1.GroupVersion.Version, releaseSeries.Contract, providerVersion)
```suggestion
		return nil, errors.Errorf("current version of clusterctl is only compatible with %s providers, detected %s for provider version %s", clusterv1.GroupVersion.Version, releaseSeries.Contract, providerVersion)
```

2022-01-19 08:52 UTC, ykakarap commented on cmd/clusterctl/client/config.go
> +	latestMetadata, err := repositoryClientFactory.Metadata(providerVersion).Get()
This command is also supposed to work when a user does not provider a version in the input (Example: `clusterctl generate provider -i aws`). In such cases the `providerVersion` here will be empty and this command will fail. If the user does not provider a version we have to fall back to the default version.

However, I see that the repository client here does not have a `DefaultVersion` function. I would suggest adding a `DefaultVersion` function to the repository.Client interface and to the implementation (`type repositoryClient struct {...}`).
You can have something like this:
```go
func (c *repositoryClient) DefaultVersion() string {
	return c.repository.DefaultVersion()
}
```
@fabriziopandini Thoughts about adding the `DefaultVersion` function to `repository.Client` interface? This interface already has a `GetVersions` function. I dont think it is unreasonable to add a `DefaultVersion` function.


Then, once you have access to the DefaultVersion function, after l.63 you can have to check to see if `providerVersion` is empty and set it to default version. This should fix the broken use case.

2022-02-16 15:40 UTC, tharun208 commented
@ykakarap will address the feedbacks this week

2022-05-07 01:28 UTC, ykakarap commented
@tharun208 will you have bandwidth to follow up on this?

2022-06-07 17:09 UTC, vincepri commented
Any updates on this PR?

2022-06-07 17:15 UTC, tharun208 commented
@ykakarap can you follow up on this pr?

2022-06-07 17:22 UTC, ykakarap commented
> @ykakarap can you follow up on this pr?

I am not sure I understand. If you are asking about the next steps to do then the review on the PR still valid. Adding those changes should be a good place to start.
Let me know if you need help with this.

2022-07-01 09:29 UTC, sbueringer commented
@tharun208 Do you have time to address the findings?

2022-07-06 22:16 UTC, vincepri commented
Going to close this for now due to inactivity, please feel free to reopen
/close

2022-07-06 22:16 UTC, closed without merging