Validate OWNERS files - remove sections about emeritus reviewers.
kubernetes-sigs/cluster-api pull request #5964
Opened 2022-01-21 08:58 UTC by peizhouyu

please see [kubernetes/community#6334](https://github.com/kubernetes/community/issues/6334)

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

What type of PR is this?   

/kind cleanup

What this PR does / why we need it:

Which issue(s) this PR fixes: 

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?  
```
NONE
```
Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:
```

```

2022-01-21 09:03 UTC, fabriziopandini reviewed
/lgtm

2022-01-21 09:03 UTC, fabriziopandini commented
/ok-to-test

2022-01-21 11:41 UTC, killianmuldoon commented
/lgtm

Just wondering why the signoff in the PR description is:
> Signed-off-by: Davanum Srinivas davanum@gmail.com

I don't think it matters - is it just copy-paste?

2022-01-21 13:13 UTC, sbueringer commented
/lgtm
 
> Just wondering why the signoff in the PR description is:
> 
> > Signed-off-by: Davanum Srinivas [davanum@gmail.com](mailto:davanum@gmail.com)
> 
> I don't think it matters - is it just copy-paste?

@peizhouyu Can you please remove it from the PR description? Thank you :)

2022-01-21 15:35 UTC, peizhouyu commented
> /lgtm
> 
> > Just wondering why the signoff in the PR description is:
> > > Signed-off-by: Davanum Srinivas [davanum@gmail.com](mailto:davanum@gmail.com)
> > 
> > 
> > I don't think it matters - is it just copy-paste?
> 
> @peizhouyu Can you please remove it from the PR description? Thank you :)
Thanks for spotting the problem, I't was removed.
Thank you

2022-01-24 06:54 UTC, mkumatag requested changes

2022-01-24 06:54 UTC, mkumatag commented on OWNERS
> +  - davidewatson
add a newline here in the end

2022-01-24 07:03 UTC, peizhouyu commented on OWNERS
> +  - davidewatson
> add a newline here in the end
I've already added it，Thanks.

2022-01-24 07:34 UTC, mkumatag reviewed
/lgtm

2022-01-24 11:17 UTC, sbueringer commented
/lgtm

2022-01-24 11:30 UTC, fabriziopandini reviewed
/lgtm
/approve

2022-01-24 11:39 UTC, merged