📖 Improve version support documentation
kubernetes-sigs/cluster-api pull request #6122
Opened 2022-02-14 12:12 UTC by fabriziopandini

**What this PR does / why we need it**:
Improving version support matrix to better surface the practices we are following.
TL;DR; we try to go over and behind Kubernetes support matrix to meet the users where they are, but at the same time there should be boundaries to what we can reasonably support/validate with our CI signal. 

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4444

/cc @CecileRobertMichon @vincepri @enxebre @sbueringer

2022-02-14 16:02 UTC, killianmuldoon requested changes

2022-02-14 17:01 UTC, vincepri approved these changes
/approve

2022-02-16 18:26 UTC, stmcginnis reviewed
/lgtm

2022-02-16 18:49 UTC, enxebre commented
/lgtm

2022-02-17 04:35 UTC, vincepri commented
/hold cancel
/approve

2022-02-17 04:47 UTC, merged

2022-02-18 11:47 UTC, fabriziopandini commented
/cherry-pick release-1.1
given that this can help the users to better understand our support matrix