✨ clusterctl: allow Namespace objects in topology plan input
kubernetes-sigs/cluster-api pull request #6257
Opened 2022-03-04 08:52 UTC by apricote

**What this PR does / why we need it**:

Adds support for `Namespace` objects in `clusterctl alpha topology plan` input. Previously it would have counted as another unique namespace, but now we just add the `metadata.name` of the `Namespace` into the set of unique namespaces.

**Which issue(s) this PR fixes**:
Fixes #6236

2022-03-04 15:32 UTC, sbueringer commented
/ok-to-test

2022-03-04 21:23 UTC, fabriziopandini commented
/lgtm
@ykakarap PTAL

2022-03-07 12:05 UTC, sbueringer commented
/lgtm

2022-03-07 13:01 UTC, ykakarap requested changes
You will need to adjust the logic in `setMissingNamespaces` function to skip `Namespace` objects.

2022-03-07 13:02 UTC, ykakarap commented
/hold

2022-03-07 13:55 UTC, apricote commented
Added a check to `setMissingNamespaces` and adopted the check from https://github.com/kubernetes-sigs/cluster-api/blob/01957390401fefe61d0e4d70c2e1c643b0ee6838/cmd/clusterctl/client/cluster/components.go#L159 to be consistent within the module.

2022-03-07 14:07 UTC, sbueringer commented
/lgtm

2022-03-07 14:07 UTC, ykakarap approved these changes
/lgtm

2022-03-07 17:50 UTC, ykakarap commented
/hold cancel

2022-03-07 17:54 UTC, fabriziopandini commented
/cherry-pick release-1.1

2022-03-07 17:54 UTC, merged