📖  docs: update the release-1.5.md with release team info
kubernetes-sigs/cluster-api pull request #8416
Opened 2023-03-29 16:22 UTC by joekr

**What this PR does / why we need it**:
This adds the new release team info for the 1.5 release docs

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

2023-03-29 16:25 UTC, ykakarap reviewed
The formatting seems off.

2023-03-29 18:16 UTC, joekr commented
> The formatting seems off.

great catch. Should be updated now.

2023-03-30 08:17 UTC, furkatgofurov7 requested changes
CI Signal/Bug Triage/Automation Manager shadows seem to have a duplicate name

2023-03-30 08:56 UTC, killianmuldoon commented on docs/release/releases/release-1.5.md
> +| CI Signal/Bug Triage/Automation Manager   | killian Muldoon ([@killianmuldoon](https://github.com/killianmuldoon) ✉️ `@Killian`) | Tobias Giese ([@tobiasgiese](https://github.com/tobiasgiese) ✉️ `@
```suggestion
| Release Lead                              | Joe Kratzat ([@joekr](https://github.com/joekr) ✉️ `@Joe Kratzat`) | Furkat Gofurov ([@furkatgofurov7](https://github.com/furkatgofurov7) ✉️ ️`@Furkat Gofurov`) <br> Prajyot Parab ([@Prajyot-Parab](https://github.com/Prajyot-Parab) ✉️ ️`@Prajyot Parab`) <br> Deepak Sharma ([@sadysnaat](https://github.com/sadysnaat) ✉️ `@Deepak Sharma`)                                               |
| Communications/Docs/Release Notes Manager | Nawaz Hussain Khazielakha ([@nawazkh](https://github.com/nawazkh) ✉️ `@nawazkh`)                                | Guillermo Gaston ([@g-gaston](https://github.com/g-gaston) ✉️ ️`@ggaston`) <br> Johannes Frey ([@johannesfrey](https://github.com/johannesfrey) ✉️ ️`@jotef`) <br> Amit Kumar ([@hackeramitkumar](https://github.com/hackeramitkumar) ✉️ `@Amit Kumar`)                             |
| CI Signal/Bug Triage/Automation Manager   | Killian Muldoon ([@killianmuldoon](https://github.com/killianmuldoon) ✉️ `@Killian`) | Tobias Giese ([@tobiasgiese](https://github.com/tobiasgiese) ✉️ `@tobiasgiese`) <br> muhammad adil ghaffar ([@adilGhaffarDev](https://github.com/adilGhaffarDev) ✉️ `@adil`) <br> Christian Schlotter ([@chrischdi](https://github.com/chrischdi) ✉️ `@chrischdi`) <br> Aniruddha Basak ([@aniruddha2000](https://github.com/aniruddha2000) ✉️ `@aniruddha`) |
```

2023-03-30 12:45 UTC, killianmuldoon reviewed
/lgtm

2023-03-31 12:42 UTC, fabriziopandini commented
/lgtm
/approve
🥳

2023-03-31 13:01 UTC, merged