📖 Add In-place upgrades feature group
kubernetes-sigs/cluster-api pull request #9559
Opened 2023-10-16 19:54 UTC by g-gaston

**What this PR does / why we need it**:
As proposed in office hours, creating a working group to work together in a proposal.

**Which issue(s) this PR fixes**:
Starting with https://github.com/kubernetes-sigs/cluster-api/issues/9489

/area documentation

2023-10-17 05:58 UTC, mayur-tolexo commented
I would like to be a part of this.

2023-10-17 12:58 UTC, fabriziopandini commented
/lgtm

Great to see this happening!
I personally think this is the right time for the project to look into this, looking forward to see this moving forward

2023-10-17 13:02 UTC, fabriziopandini commented
/hold 
for the meeting time to be added + give others time to review

2023-10-17 13:40 UTC, killianmuldoon reviewed
/lgtm

Looking forward to seeing what comes from this work!

2023-10-17 14:30 UTC, vincepri commented on docs/community/20231016-in-place-upgrades.md
> +- Guillermo Gaston (@g-gaston, AWS)
Could you add @sdodson and myself to this list?

2023-10-18 08:05 UTC, dharmjit commented on docs/community/20231016-in-place-upgrades.md
> +title: Feature Group for Managed Kubernetes in Cluster API
```suggestion
title: Feature Group for In-place Upgrades support in Cluster API
```

2023-10-18 08:06 UTC, dharmjit commented on docs/community/20231016-in-place-upgrades.md
> +    - "@sbueringer”"
typo
```suggestion
    - "@sbueringer"
```

2023-10-18 14:41 UTC, g-gaston commented on docs/community/20231016-in-place-upgrades.md
> +- Alexander Demicev (@@alexander-demicev, SUSE)
🤦🏻

2023-10-20 14:48 UTC, g-gaston commented
Meeting and google doc added, I think this is ready to go :)
/unhold

2023-10-20 17:41 UTC, furkatgofurov7 requested changes
Few last nits we need to fix :)

2023-10-20 17:41 UTC, furkatgofurov7 commented on docs/community/20231016-in-place-upgrades.md
> +We will meet on [Wednesdays at 08:00 PT (Pacific Time)][zoomMeeting]. [Convert to your timezone](https://dateful.com/time-zone-converter?t=09:00&tz=PT%20%28Pacific%20Time%29). Meeting notes will be d
I think you are missing to add `zoomMeeting` reference at the end.

2023-10-20 17:41 UTC, furkatgofurov7 commented on docs/community/20231016-in-place-upgrades.md
> +- Dharmjit Singh (@dharmjit, VMware)
```suggestion
- Dharmjit Singh (@dharmjit, VMware)

[zoomMeeting]: https://zoom.us/j/861487554
```

2023-10-20 17:41 UTC, furkatgofurov7 commented on docs/community/20231016-in-place-upgrades.md
> +Regular, summarized updates of group progress will be provided during weekly Cluster API office hours on Wednesdays @ 10:00 PT.
```suggestion
Regular, summarized updates of group progress will be provided during weekly Cluster API office hours on Wednesdays @ 10:00 PT on [Zoom][zoomMeeting].
```

2023-10-20 19:11 UTC, furkatgofurov7 reviewed
Thank you @g-gaston!

/lgtm

2023-10-20 19:43 UTC, Oats87 commented
I would love to also be a part of this!

2023-10-20 21:39 UTC, g-gaston commented
> I would love to also be a part of this!

We'll be meeting Wednesdays at 8am PST in https://zoom.us/j/861487554
Pls join us!

2023-10-25 16:09 UTC, Oats87 commented
> > I would love to also be a part of this!
> 
> We'll be meeting Wednesdays at 8am PST in https://zoom.us/j/861487554 Pls join us!

Apologies for not joining. I was told "one hour before CAPI meeting" and had assumed it was at 9 AM PST rather than 8 AM PST.

I will do my best to join it next week!

2023-10-25 16:53 UTC, sbueringer commented
This seems fine to me. Should we merge @vincepri @fabriziopandini ?

/lgtm

2023-11-02 06:08 UTC, pshail commented
I also would love to be a part of this effort

2023-11-02 15:07 UTC, fabriziopandini reviewed
/lgtm
/approve

Awesome folks!

2023-11-02 15:25 UTC, merged